### ISSUE TITLE
關於更改字型

### ISSUE THREAD

**Issue by s86097john** [pcman-bbs/pcman-windows#1]
不好意思，不知道這個問題適不適合放在這裡，就是我想要在 windows 版的pcman上面使用思源黑體，
但是我只有看到如附檔的這幾種字體 。

請問我可以去哪裡設定? 或是我可以更改source code 的哪個部分以達到我的需求? 

如果這個問題不適合放在這邊，就請關閉它吧。打擾了。

![52](https://cloud.githubusercontent.com/assets/5384407/15152903/ab32edf4-1709-11e6-8c74-d23ba6b9deb7.PNG)

**Comment by SUCM** [comment]
可以使用等距更紗黑體 T TC
https://github.com/be5invis/Sarasa-Gothic/releases
