### ISSUE TITLE
NonFree 圖示

### ISSUE THREAD

**Issue by robertabcd** [pcman-bbs/pcman-windows#11]
@PCMan 這個可能又要召喚了 m(_ _)m
Project readme 是說因為授權問題無法 check-in，想問問是什麼樣的授權問題？如果是圖示包成壓縮檔放到 release，之後 CI build 時候下載下來換過去會不會有授權問題？

**Comment by kidwm** [comment]
直接找一套換掉吧，Material Icons 之類的？

**Comment by PCMan** [comment]
@robertabcd 我記得之前的 icon 是原作者直接授權我們使用，但他不是 GPL 授權，所以沒有一起放進 source code 以 GPL 釋出。
類似的狀況 mozilla 也是一樣，firefox source code 裡面沒有 firefox 的 icon，但是官方版本會是 firefox icon。
是說我記得最早以前有放進去...後來不知道誰拿掉了

**Comment by robertabcd** [comment]
我把圖示單獨弄出來放到 9.4.2 Release 裡了
