### ISSUE TITLE
PCMan 9.5.0 Beta websockets 模式無法貼上大量文字

### ISSUE THREAD

**Issue by ccpz** [pcman-bbs/pcman-windows#16]
[titleformat_help.zip](https://github.com/pcman-bbs/pcman-windows/files/1312670/titleformat_help.zip)

例如此 html 檔案 (只是範例，只要任何多頁文字一次複製都不行)
用 ansi 編輯->開啟舊檔
然後按右鍵->全選整個緩衝區

使用 websocket 連上 ptt 時無法貼上，
但 telnet 就可以。

**Comment by robertabcd** [comment]
我剛測試是單選一頁或是某小段時可以複製貼上。在全選整個緩衝區的時候不行。
測試另一個較小的檔案，三種都可貼上成功。
我想可能是複製文字太常造成 Websocket 處理哪邊 drop 了。

**Comment by robertabcd** [comment]
發現是之前弄到一半忘記實作
於 a1bdedd5a85110c0d99f7c73ff96310c2ff0316d 已修正
