### ISSUE TITLE
Websocket 無法連線時，視窗凍結 (blocking DNS resolution)

### ISSUE THREAD

**Issue by eight04** [pcman-bbs/pcman-windows#17]
1. 點擊位址欄
2. 輸入一個不存在的位址，如︰`wss://ws.ptt.cd/bbs`
3. 按 Enter

把網路斷掉再連 `wss://ws.ptt.cc/bbs` 也有同樣效果。

9.5.0 beta

**Comment by robertabcd** [comment]
請問你的系統是？

**Comment by eight04** [comment]
Windows 7 x64

**Comment by robertabcd** [comment]
我猜測是 Websocket 那邊做 synchronized DNS query，然後 UI 這邊又想要傳資料，等 lock 的關係。
要改成 async 需要動 websocket library，並不是很好改。
或許可以朝 UI 傳資料可以不用 lock 方向改。

**Comment by robertabcd** [comment]
Duplicate as #37
