### ISSUE TITLE
詢問看看這個Repository和ptt的PCMan板是同個專案嗎？

### ISSUE THREAD

**Issue by name2name2** [pcman-bbs/pcman-windows#2]
冒昧打擾，想詢問看看這個Repository和ptt的PCMan板是同個專案嗎？
最近有人提到OpenFoundry停止服務，
想說有沒有是原開發者可以協助遷移，謝謝！

┌─────────────────────────────────────┐
│ 文章代碼(AID): #1OUA5MZy (PCman) [ptt.cc] [問題] OpenFoundry專案託管服務 │
│ 文章網址: https://www.ptt.cc/bbs/PCman/M.1484300630.A.8FC.html           │
│ 這一篇文章值 0 Ptt幣                                                     │
└─────────────────────────────────────┘
>  6303   1 1/13 AshenC       □ [問題] OpenFoundry專案託管服務於2016年底終止

**Comment by kidwm** [comment]
是

**Comment by name2name2** [comment]
謝謝回覆  (單純熱心發問，我平常也使用pcman

目前進入看板置底文章9.4.2下載連結的確變成錯誤畫面，
![image](https://cloud.githubusercontent.com/assets/10517310/21955764/6b62320e-daac-11e6-91bb-0638faa0918e.png)

不知道你們能不能在GitHub整理出和Foundry一樣的新的各版本下載清單列表連結，
方便下載者選擇要下載的版本呢，謝謝



...
### 看板置底文章如下

 作者  cole945 (躂躂..)                                           看板  PCman
 標題  [情報] PCMan 9.4.2
 時間  Sat Mar 30 23:18:25 2013
───────────────────────────────────────
因為最近比較忙, 結果拖了很久 orz

請到這裡下載 9.4.2
http://www.openfoundry.org/of/projects/744/download

主要是把上篇到提的問題修正了
另外補了兩個小功能
┌─────────────────────────────────────┐
│ 文章代碼(AID): #1HLm94hW (PCman) [ptt.cc] [情報] PCMan 9.4.2             │
│ 文章網址: https://www.ptt.cc/bbs/PCman/M.1364656708.A.AE0.html           │
│ 特殊文章，無價格記錄                                                     │
└──────────────

**Comment by kidwm** [comment]
搬過來了。
https://github.com/pcman-bbs/pcman-windows/releases
