### ISSUE TITLE
PCMan 9.5.0 Beta 的 Websocket 安全連線不定時自動斷線

### ISSUE THREAD

**Issue by gcobc12632** [pcman-bbs/pcman-windows#21]
系統：Win10

版本：PCMan 9.5.0 Beta 免安裝版（非CB版）

在連 wss://ws.ptt.cc/bbs 的時候 常常會不定時自動斷線

這是正常的情況嗎？

我有設定一些自動回訊來做自動登入

這跟我取消閒置180秒後送出字串有關係嗎？

**Comment by eight04** [comment]
不知是否相關，我也常斷線，不過通常都是在切換頁面時發生的︰
![image](https://user-images.githubusercontent.com/1324510/30777172-a6d0d79e-a0e7-11e7-9f1e-1d4bffc7fc3c.png)

**Comment by robertabcd** [comment]
Duplicate as #37
