### ISSUE TITLE
Websocket 的自動重新連線沒有 delay

### ISSUE THREAD

**Issue by eight04** [pcman-bbs/pcman-windows#22]
剛剛 05:00 PTT 關機後，按下 Enter 重新連線，發現左上角的圖示不斷閃爍。查看資源監視器，被 PCMan 洗板︰
![image](https://user-images.githubusercontent.com/1324510/30777149-37ca68b0-a0e7-11e7-8e0a-98bf78b4d9a1.png)

**Comment by robertabcd** [comment]
這是自動重新連線預設 0 秒的關係。已於 fb833e3ef80585d2ad875eb4924cddd4c1df1feb 修正。
