### ISSUE TITLE
libwebsockets.h, lws_config.h not found when building project

### ISSUE THREAD

**Issue by Yang09701194** [pcman-bbs/pcman-windows#23]
Hi, I have installed VS2017 and build the _pcman-windows_ project.
but got errors: 
 `cannot open source file "libwebsockets.h"   - at   Combo \pcman-windows\Lite\Websocket.cpp	10`	
 `Cannot open include file: 'lws_config.h': No such file or directory`,

I try to serach these files under the solution folder but result is not found,
So I suggest that these two files could be included in the repository.

I hope anyone can build the poject after installing  vs2017 and standard library , 
For the files that aren't in the standard library, they could be placed into the repository, thank you.

--------

More detail:

I'm new at C++, and I find that `libwebsockets.h` possibly comes from a github project `warmcat/libwebsockets`, but I cannot find `lws_config.h`, so I can't pass building.

I find that the `libwebsockets.h` file can be auto included by VS by adding file to `SimpXmlParser` folder under project . If it's correct, I suuggest adding `libwebsockets.h, lws_config.h` files to `SimpXmlParser` folder.

------------

Error Screenshot:

![image](https://user-images.githubusercontent.com/23180780/30784958-294aa7d2-a191-11e7-926b-dfc89f67ef95.png)

![image](https://user-images.githubusercontent.com/23180780/30785254-acc86af4-a196-11e7-95f2-a112a807c623.png)

**Comment by robertabcd** [comment]
You need to install libwebsockets 2.2.1 or later. In CI, we use [Microsoft/vcpkg](https://github.com/Microsoft/vcpkg) to install this library along with its dependencies. However, vcpkg ships with 2.0.0, we have a patch here at `hack/portfile.cmake`, please look at `Scripts/BeforeBuild.ps1` for the path to patch.

**Comment by ras0219-msft** [comment]
@robertabcd We'd be happy to accept a PR updating libwebsockets so you don't need local patches :)
