### ISSUE TITLE
請移除kkcity from default 我的最愛

### ISSUE THREAD

**Issue by frank-hsieh** [pcman-bbs/pcman-windows#25]
kkcity 已不再提供bbs了

**Comment by Yang09701194** [comment]
看到這次更新才發現這個issue，容我留一點想法，個人覺得留下一些已關閉的知名BBS連結對於後面新加入BBS的朋友，能夠對BBS歷史和架構有更多的接觸和認識，不過只是提供想法參考，沒有說非常傾向怎麼做的意思

**Comment by holishing** [comment]
@Yang09701194 若有意協助管理相關資訊，歡迎至 [bbslist/bbslist.github.io](https://github.com/bbslist/bbslist.github.io)，提供寶貴意見
