### ISSUE TITLE
Websocket rework

### ISSUE THREAD

**Issue by robertabcd** [pcman-bbs/pcman-windows#37]
先前使用的 libwebsocket 有許多問題，像是：

- 使用 blocking DNS resolution
- 需要自己提供 root certs 檔案
- 開發文件不太完善，有些 API 無法不知如何使用
- 些許不穩定

目前找了 https://github.com/microsoft/cpprestsdk 使用上穩定度看起來沒問題
但是最低系統需求要提升成 Windows 7 SP1 以上
目前我自己在 https://github.com/robertabcd/pcman-windows/tree/wsrework 這個分支開發

**Comment by craftwar** [comment]
Win7以上不是問題吧，都哪年代了，支援XP不重要了
開發者也不可能弄XP來支援
我自己用的版本已經拿掉XP支援，改dynamic link MFC dll了

**Comment by robertabcd** [comment]
我也覺得不用繼續支援 XP 了

**Comment by kidwm** [comment]
直接拿掉支援吧，到時新版發了記得提醒我在網頁上說明一下

**Comment by robertabcd** [comment]
Merged.
