### ISSUE TITLE
自訂快速鍵功能無法儲存

### ISSUE THREAD

**Issue by robertabcd** [pcman-bbs/pcman-windows#38]
修改 BuildMenu 的時候把讀寫 UI 檔的部分砍了

在 Issue #8 裡大神說可以做成
```
[Hotkeys]
1001=Ctrl+O
1002=Alt+D
```
的形式

我也在考慮要不要直接刪除自訂快速鍵的功能
現在 app 好像都不提供這種功能了

**Comment by kidwm** [comment]
可以先丟個移除自訂功能的測試版出來看看有沒有人抱怨

**Comment by robertabcd** [comment]
Hmm 好像有寫儲存功能 d5982892cc2ef053c94fdaef607356614aeb8247
只是我測試的時候好像是壞的 XD
有空再 debug 看看

**Comment by robertabcd** [comment]
Fixed as 0e84215296bee18cc2a85989810954612aa61126
