### ISSUE TITLE
win10升級1909版本之後，pcman程式顯示亂碼

### ISSUE THREAD

**Issue by redwildwing** [pcman-bbs/pcman-windows#40]
win10升級1909版本之後，pcman程式全部變成亂碼
包含選項列、指令列、BBS畫面等
都無法正常顯示

請參考下方畫面截圖：
https://imgur.com/Mr5ohxb

**Comment by idaidaponpon** [comment]
這是windows字形設定跑掉 基本上要去設定看看有沒有用中文字型
