### ISSUE TITLE
Compile Error Question

### ISSUE THREAD

**Issue by name2name2** [pcman-bbs/pcman-windows#48]
Hi, recently I try to build this project again but got error, hope someone can help. I clone this project last few days, and have learned to install and use `vcpkg` , and installed many packages, also google keyword to solve many errors and  problems such as error related to  `Project > Properties > Linker > Additional Dependencies` settings.

Now I got an error that after google I still can't solved:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: class Concurrency::task<class web::websockets::client::websocket_incoming_message> __thiscall web::websockets::client::details::websocket_client_task_impl::receive(void)" (__imp_?receive@websocket_client_task_impl@details@client@websockets@web@@QAE?AV?$task@Vwebsocket_incoming_message@client@websockets@web@@@Concurrency@@XZ) referenced in function "public: class Concurrency::task<class web::websockets::client::websocket_incoming_message> __thiscall web::websockets::client::websocket_client::receive(void)" (?receive@websocket_client@client@websockets@web@@QAE?AV?$task@Vwebsocket_incoming_message@client@websockets@web@@@Concurrency@@XZ)	Combo	\pcman-windows\Combo\Websocket.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: void __thiscall web::websockets::client::details::websocket_client_task_impl::close_pending_tasks_with_error(class web::websockets::client::websocket_exception const &)" (__imp_?close_pending_tasks_with_error@websocket_client_task_impl@details@client@websockets@web@@QAEXABVwebsocket_exception@345@@Z) referenced in function __catch$??R<lambda_6faaa49c60b61750ef16c4ff707b1ae7>@@QBE@V?$task@X@Concurrency@@@Z$0	Combo	\pcman-windows\Combo\Websocket.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __thiscall web::websockets::client::details::websocket_client_task_impl::websocket_client_task_impl(class web::websockets::client::websocket_client_config)" (__imp_??0websocket_client_task_impl@details@client@websockets@web@@QAE@Vwebsocket_client_config@234@@Z) referenced in function "public: __thiscall std::_Ref_count_obj<class web::websockets::client::details::websocket_client_task_impl>::_Ref_count_obj<class web::websockets::client::details::websocket_client_task_impl><class web::websockets::client::websocket_client_config>(class web::websockets::client::websocket_client_config &&)" (??$?0Vwebsocket_client_config@client@websockets@web@@@?$_Ref_count_obj@Vwebsocket_client_task_impl@details@client@websockets@web@@@std@@QAE@$$QAVwebsocket_client_config@client@websockets@web@@@Z)	Combo	\pcman-windows\Combo\Websocket.obj	1	
Error	LNK2019	unresolved external symbol _CONF_modules_unload referenced in function "public: __thiscall boost::asio::ssl::detail::openssl_init_base::do_init::~do_init(void)" (??1do_init@openssl_init_base@detail@ssl@asio@boost@@QAE@XZ)	Combo	\pcman-windows\Combo\Websocket.obj	1	
Error	LNK2019	unresolved external symbol _ERR_reason_error_string referenced in function "public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall boost::asio::error::detail::ssl_category::message(int)const " (?message@ssl_category@detail@error@asio@boost@@UBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z)	Combo	\pcman-windows\Combo\Websocket.obj	1	

```

I guess this error is related to `cpprest` because in `Websocket.cpp` it includes `<cpprest/ws_client.h>`, but I have add lib `cpprest_2_10.lib` to `Linker > Additional Dependencies` but still show these errors.

How to solve the Error?  all the packages such as `cpprest` and `boost` are latest, installed by `vcpkg`.

Can you build success recently? Thank you very much!

**Comment by name2name2** [comment]
對C++還不熟悉，這幾天又再發起一波嘗試，經過辛苦的網路搜尋，本來還想說已經盡力了還是沒招@@，打算去相關看板發問了，好在後來有搜到關鍵的相關好心大大教學，總算找到原來 `unresolved external symbol`  是一種固定常見的C++錯誤訊息，跟 `C++ 有declaration 但沒有definition`  有關，另外也對於其他遇到的問題大量搜尋試誤解決，也有初步開始使用CMake，目前拼拼湊湊已經可以成功讓Lite專案跑起來，但拼湊的過程還差一點，`websocket_client_task_impl` 還沒透徹解決，差一點繼續摸索中。之後如果真的完全跑起來了，可能打算看用什麼方式分享過程，讓新接觸的人也可以建置成功跑起來，也可以跟目前repo的前面貢獻者交流一下我的方式和觀念有沒有可以改進的地方，我算是還是C++新新手。但是要等我真的把最後的`websocket_client_task_impl`透徹解決，還不確定能不能完全通這一段。不保證要花多少時間和最後能不能成功。我也是在很少可用的時間裡抽出時間來試的，不保證能經常花時間在這個issue，假若有空有閒就可以再試一下。
.
![](https://i.imgur.com/68zihze.png)

**Comment by holishing** [comment]
是不是少了 `libwebsockets` 這個套件啊? 看 @craftwar 的 patch 猜的，還沒編過去不太確定

**Comment by holishing** [comment]
https://github.com/craftwar/pcman-windows/commit/a06be1c9104c1117bf8700365bd86cc8d1437a1e

~~看起來是這個問題? 只是這個 patch 用的解法是把 libwebsockets 降版 v2.2.1 來解決，不知道有沒有不要降版的方法?~~

不過看起來 websocket 的功能靠 cpprestsdk 就應該可以搞定了

**Comment by name2name2** [comment]
剛才再試了一段時間已經可以完全成功跑起來了，原始碼都沒問題，我再整理一下依據 [Dependency.txt](https://github.com/pcman-bbs/pcman-windows/blob/master/Dependencies.txt) 和  我發現的像我這樣的新新手需要教學的其他步驟    大約需要幾天的時間

**Comment by robertabcd** [comment]
現在 HEAD 是用 `cpprestsdk` 裡的 websocket support，已經不用 `libwebsockets` 了

**Comment by robertabcd** [comment]
我記得是不用自己加 `.lib` 到 dependency 裡，設成 dynamic runtime 他會自己抓正確的 DLL 來用。可能是因為你加了 `cpprest_2_10.lib` 才出現這個問題。

**Comment by name2name2** [comment]
感謝回覆，我昨天繞了很多路和很多嘗試後最後找到能跑起來找到的主要解法是這篇  (還有混合其他一些文章的概念做法) ：
https://stackoverflow.com/questions/2694994/opencv-dll-missing-but-its-not 

看到後得到啟發我的做法是  

1.  一樣在 Project > Properties > Linker > Additional Dependencies 加上  cpprest_2_10.lib 路徑
2.  用CMake去跑 cpprestsdk repo原始碼，得到了能用vs開啟的原始方案檔 sln vcxproj等等，再用vs開起來後建置在\Binaries\Debug得到的dll  (包括libcrypto-1_1.dll  cpprest141_2_10d.dll  libssl-1_1.dll  zlibd1.dll boost_date_time-vc141-mt-gd-x32-1_72.dll) 
再依照上方文章教學，複製到Lite和Combo專案資料夾中

就兩個專案都可以跑起來了

.
感謝分享做法，Dynamic Runtime 我 google 好像找不到明顯的設定方式，請問大概要那些步驟去設定?
https://www.google.com/search?rlz=1C1CHBF_zh-TWTW793TW793&sxsrf=ALeKk01AgD0dkKn47o-nfYMQRtss3ldcvA%3A1590150915774&ei=A8fHXoTmLseUr7wPhu2D8A4&q=C%2B%2B+visual+studio+dynamic+runtime&oq=C%2B%2B+visual+studio+dynamic+runtime&gs_lcp=CgZwc3ktYWIQAzIECCMQJzoGCAAQCBAeOgcIIxCwAhAnOggIABAIEA0QHlD7yQFYq8wBYMrPAWgDcAB4AIABbIgBqAWSAQM2LjKYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwjE8-TjvcfpAhVHyosBHYb2AO4Q4dUDCAw&uact=5

**Comment by name2name2** [comment]
PCMan程式專案建置和執行：逐步解說
---
1. 安裝 Visual Studio 2017 (Community 即可)
   * 請至官方網站下載: https://www.visualstudio.com/    
   * 目前最新版本是Visual Studio 2019 應該也可以
   * 安裝過程詢問到要安裝那些模組時，將C++有關的套件選項都勾起來安裝，依照安裝程式導引安裝完成
   
1. 建立一個本機資料夾可以放git repository，以下將資料夾路徑代稱為 `本機Git資料夾`

1. git clone pcman-windows (https://github.com/pcman-bbs/pcman-windows.git) 到 `本機Git資料夾\pcman-windows`
   * 可以用git的clone指令，或者git的相關GUI軟體的clone功能

1. git clone vcpkg (https://github.com/Microsoft/vcpkg) 到 `本機git資料夾\vcpkg`
   * clone完成後，依照官方頁面教學，點兩下執行 vcpkg\bootstrap-vcpkg.bat
   * 執行完成後會出現 vcpkg\vcpkg.exe
   * 開啟cmd，執行`cd /d 本機Git資料夾\vcpkg`，再執行`vcpkg integrate install`
      * 正確會印出訊息 `Applied user-wide integration for this vcpkg root.` 
      * 如果出現 `Warning: integration was not applied`，則將整個vcpkg資料夾複製到C:\ ，再執行`vcpkg integrate install`。後面步驟的vcpkg路徑都要改成 C:\vcpkg  [[註1]](#remark)

1. 使用vcpkg安裝套件
   * 將cmd的路徑保持在`本機Git資料夾\vcpkg`，以下開始用cmd安裝x86版本的pacakage
   * 執行`vcpkg install cpprestsdk:x86-windows`
   * 執行`vcpkg install boost:x86-windows`，裝的套件比較多，耐心等候大約半小時安裝完成
   * 執行`vcpkg install websocketpp:x86-windows`

1. git clone cpprestsdk (https://github.com/microsoft/cpprestsdk) 到 `本機git資料夾\cpprestsdk`
 
1. 安裝CMake
   * 前往 https://cmake.org/download/ ， 下載Latest Version中適用於Windows x64的msi檔
   * 執行msi檔，跟隨安裝程式導引完成CMake安裝

1. 取得cpprestsdk相關的dll lib檔 
   * cmd 執行 `cd /d 本機Git資料夾\cpprestsdk`
   * 執行 `mkdir build.x32v141` [[註2]](#remark)
   * 執行 `cd build.x32v141`
   * 執行 `"C:\Program Files\CMake\bin\cmake.exe" ../Release -A Win32 -DCMAKE_TOOLCHAIN_FILE=本機Git資料夾/vcpkg/scripts/buildsystems/vcpkg.cmake`
      * 正確完成會印出訊息 `Build files have been written to: 本機Git資料夾/cpprestsdk/build.x32v141`
   * 用 visual studio 開啟 `\build.x32v141\cpprestsdk.sln`
   * 等待 visual studio 載入專案，左下角如有` Parsing Include ... Scanning Include ...` 訊息，耐心等候直到左下角訊息停止變動，出現`就緒 Ready`訊息
   * 在 cpprest 專案 > 右鍵 > Build(建置) ，等待建置成功
   * 建置成功後，會有一些`.dll .lib`等等檔案輸出到`\build.x32v141\Binaries\Debug`，全部的檔案有`cpprest141_2_10d.dll libcrypto-1_1.dll libssl-1_1.dll zlibd1.dll cpprest141_2_10d.exp cpprest141_2_10d.ilk cpprest141_2_10d.lib cpprest141_2_10d.pdb`
   * 將這些檔案複製到 `本機Git資料夾\pcman-windows\Lite` 和 `本機Git資料夾\pcman-windows\Combo` 
   
1. 設定/建置PCMan專案
   * 用 visual studio 開啟 `本機Git資料夾\pcman-windows\PCMan.sln`
   * 開啟後等待 visual studio 載入，等到左下角訊息不再變動
   * 在 Combo 專案 > 右鍵 > Properties(屬性) > Linker > All Options > 設定頁面往上滾動 > Additional Dependencies > 在現有參數後方加上 `本機Git資料夾\pcman-windows\Combo\cpprest141_2_10d.lib;` ， 小心不要覆蓋掉全部的值(發現蓋掉全部的值可按Esc還原)，是加在現有值的後方
   * 在 Combo 專案 > 右鍵 > Build(建置) ，等待建置成功
   * 在 Lite 專案 > 右鍵 > Properties(屬性) > Linker > All Options > 設定頁面往上滾動 > Additional Dependencies > 在現有參數後方加上 `;本機Git資料夾\pcman-windows\Lite\cpprest141_2_10d.lib` ， 小心不要覆蓋掉全部的值(發現蓋掉全部的值可按Esc還原)，是加在現有值的後方
   * 在 Lite 專案 > 右鍵 > Build(建置) ，等待建置成功

1. 執行 PCMan
   * 在 Lite 或 Combo 專案 > 右鍵 > Set as StartUp Project(設定為起始專案) > 按下 F5 ， 即可執行出現PCMan的程式畫面

.

### Remark

[註1] : 我原本先把vcpkg裝在E:\ ，然後跑`integrate install`會出現`Warning: integration was not applied`訊息，雖然看到Warning先繼續安裝相關的套件完成，安裝完成後發現在visual studio裡面的cpp檔相關的`#include`還是會出現紅線錯誤。後來搜尋 https://github.com/Microsoft/vcpkg/issues/5956 提到
`I have reinstalled vcpkg directly to the c-drive and now it is working, even if I don't know why. Thank you for the support.`，我改放到C:\底下，重新執行`integrate install`就得到`Applied user-wide integration for this vcpkg root.`訊息，cpp檔裡面的`#include`也正常了。但是刪掉vcpkg再重裝在E:\，又沒問題了。

[註2] : 從 https://github.com/microsoft/cpprestsdk/wiki/How-to-build-for-Windows 學到，裡面是x64，另外搜尋一些文章得知參數改成Win32就可以輸出為32位元的版本

**Comment by name2name2** [comment]
@robertabcd  請問我這個安裝步驟，可以幫忙看一下有無需要調整，

和是否有機會讓我做一個PR，放到README.md，或者放在Wiki然後在READMe.md加超連結連過去?  謝謝

**Comment by name2name2** [comment]
@robertabcd  @craftwar  @kidwm  請問可以幫忙看一下我上面的安裝步驟有無需要調整，

和是否有機會讓我做一個PR，放到README.md，或者放在Wiki然後在README.md加超連結連過去?  謝謝

**Comment by holishing** [comment]
能不能 `vcpkg install cpprestsdk[default-features,websockets]` 就解決相依問題呢?
參考 https://github.com/microsoft/vcpkg/blob/master/ports/cpprestsdk/CONTROL 如果有 enable `websockets` 這個 feature 的話就會自動幫你裝剩下的 `websocketpp` `boost`(只會裝相關 feature) 了

理論上都可以進 CI 了應該有更簡潔明瞭且可以自動化的配置方法才對

**Comment by holishing** [comment]
測試完 `vcpkg install cpprestsdk[default-features,websockets]` 的確可以，看起來是因為 vcpkg 把 websockets 移出 default-features 了，果然能靠相依性解決還是最好的
沒太大問題的話 @name2name2 修正完這部分之後其實可以直接發 PR

這樣修正完後應該會改成:

---

## PCMan程式專案建置和執行：逐步解說

1. 安裝 Visual Studio 2017/2019 (Community 即可)
   
   * 請至官方網站下載: https://www.visualstudio.com/
   * 安裝過程詢問到要安裝那些模組時，將C++有關的套件選項都勾起來安裝，依照安裝程式導引安裝完成

2. 建立一個本機資料夾可以放git repository，以下將資料夾路徑代稱為 `本機Git資料夾`

3. git clone pcman-windows (https://github.com/pcman-bbs/pcman-windows.git) 到 `本機Git資料夾\pcman-windows`
   
   * 可以用git的clone指令，或者git的相關GUI軟體的clone功能

4. git clone vcpkg (https://github.com/Microsoft/vcpkg) 到 `本機git資料夾\vcpkg`
   
   * clone完成後，依照官方頁面教學，點兩下執行 vcpkg\bootstrap-vcpkg.bat
   * 執行完成後會出現 vcpkg\vcpkg.exe
   * 開啟cmd，執行`cd /d 本機Git資料夾\vcpkg`，再執行`vcpkg integrate install`
     
     * 正確會印出訊息 `Applied user-wide integration for this vcpkg root.`
     * 如果出現 `Warning: integration was not applied`，則將整個vcpkg資料夾複製到C:\ ，再執行`vcpkg integrate install`。後面步驟的vcpkg路徑都要改成 C:\vcpkg  [[註1]](#remark)

5. 使用vcpkg安裝套件
   
   * 將cmd的路徑保持在`本機Git資料夾\vcpkg`，以下開始用cmd安裝x86版本的pacakage
   * 執行`vcpkg install cpprestsdk:x86-windows[default-features,websockets] `

6. git clone cpprestsdk (https://github.com/microsoft/cpprestsdk) 到 `本機git資料夾\cpprestsdk`

7. 設定/建置PCMan專案
   
   * 用 visual studio 開啟 `本機Git資料夾\pcman-windows\PCMan.sln`
   * 開啟後等待 visual studio 載入，等到左下角訊息不再變動
   * 在 Combo 專案 > 右鍵 > Build(建置) ，等待建置成功
   * 在 Lite 專案 > 右鍵 > Build(建置) ，等待建置成功

8. 執行 PCMan
    
    * 在 Lite 或 Combo 專案 > 右鍵 > Set as StartUp Project(設定為起始專案) > 按下 F5 ， 即可執行出現PCMan的程式畫面

**Comment by name2name2** [comment]
剛才在cmd試會出錯:
```
\vcpkg>vcpkg install cpprestsdk:x86-windows[default-features,websockets]
Error: <unknown>:1:23: expected eof
   on expression: cpprestsdk:x86-windows[default-features,websockets]
                                        ^
```

**Comment by holishing** [comment]
應該是 cpprestsdk[default-features,websockets]:x86-windows，上面的留言已經修正

**Comment by name2name2** [comment]
沒問題了，使用 vcpkg install cpprestsdk:x86-windows[default-features,websockets]  就可以不用手動CMake，第六步clone cpprestsdk也可以省掉，感謝 @holishing  分享

我有先在我的repo首頁的Readme.txt 更名為 Readme.md，並且加上這份說明文件的連結及相關的wiki，可以先幫我看一下有沒有要再改的，謝謝

https://github.com/name2name2/pcman-windows

https://github.com/name2name2/pcman-windows/wiki/PCMan%E7%A8%8B%E5%BC%8F%E5%B0%88%E6%A1%88%E5%BB%BA%E7%BD%AE%E5%92%8C%E5%9F%B7%E8%A1%8C%EF%BC%9A%E9%80%90%E6%AD%A5%E8%A7%A3%E8%AA%AA

**Comment by holishing** [comment]
wiki 的部分你應該可以直接編輯這邊的 [github wiki](https://github.com/pcman-bbs/pcman-windows/wiki)，已經先幫你轉貼過去了

**Comment by name2name2** [comment]
謝謝，已發出PR https://github.com/pcman-bbs/pcman-windows/pull/50

**Comment by robertabcd** [comment]
@holishing 我覺得有太多多餘的步驟，我之前只要裝好 `vcpkg` 之後用他裝 `cpprestsdk` 就好了。

**Comment by holishing** [comment]
[github wiki](https://github.com/pcman-bbs/pcman-windows/wiki/Building_PCMan) 這邊已經把多餘步驟修掉了，現在步驟跟之前不一樣的地方，只有要裝的套件名稱從 `cpprestsdk` 必須改成 `cpprestsdk[default-features,websockets]` 這樣

**Comment by holishing** [comment]
`cpprestsdk` 套件名稱需要改成 `cpprestsdk[default-features,websockets]` 的原因如下：
- https://github.com/microsoft/vcpkg/pull/10478
- https://github.com/microsoft/vcpkg/commit/056e9517ec7c461cdfabe8ff73124325708a4723

**Comment by robertabcd** [comment]
> `cpprestsdk` 套件名稱需要改成 `cpprestsdk[default-features,websockets]` 的原因如下：
> 
> * [microsoft/vcpkg#10478](https://github.com/microsoft/vcpkg/pull/10478)
> * [microsoft/vcpkg@056e951](https://github.com/microsoft/vcpkg/commit/056e9517ec7c461cdfabe8ff73124325708a4723)

不知道會不會哪天整個被移除，或許需要找別的 library...
