### ISSUE TITLE
1. 無法使用 Ctrl + 左右鍵 切換分頁 2.Crash Issue

### ISSUE THREAD

**Issue by sushitw** [pcman-bbs/pcman-windows#52]
1. 舊版是可以使用 ctrl + 左右鍵 切換分頁，但這版不行

2. 當我正常登出 web socket 連線之後按空白鍵重連會 crash

**Comment by robertabcd** [comment]
1. bug 原因同 #43 
2. 已在 1f093b495f7d5894e2f4aed61ba4407729d94e21 中修正了

Duplicate of #43
