### ISSUE TITLE
考慮使用ApppVeyor提供git builds?

### ISSUE THREAD

**Issue by craftwar** [pcman-bbs/pcman-windows#7]
[https://www.appveyor.com/](https://www.appveyor.com/)
開發者不用手動發佈，也不會有偷改程式的疑慮
只要commit到github就會自動build，上傳server
可以讓使用者更方便測試新版本

**Comment by robertabcd** [comment]
前陣子有在看這家，不過不確定有沒有時間弄

**Comment by craftwar** [comment]
visual studio的project還滿簡單的，弄到git checkout能直接build就可以上appveyor了
其實我試過直接丟上appveyor，發現websocket lib沒放進git無法build
[https://ci.appveyor.com/project/craftwar_appveyor/pcman-windows/build/1](https://ci.appveyor.com/project/craftwar_appveyor/pcman-windows/build/1)

這方面希望能修正一下，如果lib有在git上，應該是能用submodule加入
沒有就讓appveyor下載，或放一份code進git(只要checkout就能build比較方便)
看了一下Version.h的產生也該修正一下，現在不是用svn了

pcman的部份修完的話，appveyor的部份我可以幫忙處理，有寫過一點小東西時用過

**Comment by robertabcd** [comment]
libwebsockets 還有滿多 dependency 的，目前是用 vcpkg 裝的，我其實不太想把他所有 dependency 都拉進這個 repo，目前的設定流程大概是這樣：
https://github.com/pcman-bbs/pcman-windows/blob/master/Dependencies.txt

**Comment by craftwar** [comment]
我對vcpkg不熟，手上也沒有VS
AppVeyor每次都會是乾淨的新環境，總不能每次都從頭開始build，有沒有binary的安裝法
或是告訴我哪些目錄可以保留就不用重來，cache size最多只能100MB
目前是整個vcpkg root cache，obj和src也cache進去了...

先測試能不能build，暴力法先弄出一個
[https://ci.appveyor.com/project/craftwar_appveyor/pcman-windows/build/1/artifacts](https://ci.appveyor.com/project/craftwar_appveyor/pcman-windows/build/1/artifacts)

最大的問題是Pcman是ANSI，AppVeyor上當然不可能是Big5，所以會有問題，要修正成unicode
cacert.pem 也許直接放進git? 檔案很小，看起來更新頻率也不高
其他build相關的修正，現在直接在AppVeyor上改比較好測試，都弄完我才會弄成設定檔

**Comment by robertabcd** [comment]
我剛剛下載你 build 好的版本，在中文版的 Windows 10 上測試，除了沒有 cacert.pem 之外運作良好，中文顯示也沒有問題。在其他語言下的 Windows 我記得之前就無法正常顯示中文，我覺得 AppVeyor build 的版本應該跟在中文版下 VS 2017 的 build 一樣。
Build 所有東西只要 7 分鐘的話感覺滿快的？

**Comment by craftwar** [comment]
在我的win7是沒辦法用的，會有亂碼，以前版本可以用程式轉locale處理，這版不行，我無法測試
[http://i.imgur.com/OQ2AZFU.png](http://i.imgur.com/OQ2AZFU.png)

7min是不算vcpkg，已cache的狀況

**Comment by robertabcd** [comment]
我大概知道了，我的系統之前有執行過正常的版本，所以他直接使用 AppData 裡的 UI 檔。自行新增 "Portable" 檔案後他才會用 local UI，所以應該是 BuildMenu 的問題。另外連線後的 bbs terminal 是沒有問題的。

**Comment by craftwar** [comment]
[https://github.com/craftwar/pcman-windows/tree/appveyor](https://github.com/craftwar/pcman-windows/tree/appveyor)
目前的進度，需要測試的自取，沒做完的東西我覺得不適合丟PR
剩下的部份可能跟修改Pcman有關，我就無法幫忙了

**Comment by robertabcd** [comment]
應該是 cache vcpkg/installed 就可以了
我弄了一個測試的在這邊：
https://ci.appveyor.com/project/robertabcd/pcman-windows/build/10

**Comment by craftwar** [comment]
放AppVeryor cache的話會自動還原，不用自己來
Cache 'C:\projects\pcman-windows\cache\vcpkg-installed' - Restored <-已完成，你又重做一次了
有一些指令是debug用，所以我加rem關掉
libwebcokets的正確解法應該是去丟PR，讓那邊更新

我建議cacert.pem下載寫成script檔，讓不是用AppVeyor的開發者也可以處理


如果要同時build不同設定可以參考kvirc或obs，先成功一個再考慮就是了

**Comment by robertabcd** [comment]
你是說 Line 5 嗎？這是他自動的
編碼問題大概要先看 #8 要怎麼處理了

**Comment by craftwar** [comment]
if (Test-Path -Path 'cache\vcpkg-installed') {
	        New-Item -Type dir vcpkg\installed
	
	        Copy-Item cache\vcpkg-installed\* vcpkg\installed -recurse
	    }
所以我說這是多餘的，系統已經做了

其實我比較希望能改成unicode，這樣我就不用轉碼開PCMan了
印象中一堆function/class，沒用generic的，直接用ansi版本
string可能也要修

**Comment by robertabcd** [comment]
我是把 cache 放在 cache\vcpkg-installed 再 copy 進去 vcpkg
(你的 repo 用 xcopy 似乎少了什麼參數不會動，所以我自己改成這樣)
如果要改成 cache 在 vcpkg\install 然後 clone 到 vcpkg_tmp 然後 copy 進去也可

改 unicode 應該是大工程，想說先讓 build 沒問題...

**Comment by craftwar** [comment]
因為有同一個目錄clone第二次會出問題，我只好換地方再copy過去
現在cache改到vcpkg-installed，似乎就沒這問題了
我說的是你line 8~12, appveyor cache就自動做了，可以砍掉

**Comment by robertabcd** [comment]
沒有吧？AppVeyor 只是把檔案 restore 到 cache\vcpkg-installed
但是最後是要放在 vcpkg\installed
所以才要那個 copy

**Comment by craftwar** [comment]
你cahce的path設哪，就是回復到哪
應該直接設vcpkg\installed就可以了，不需要設在cache\vcpkg-installed，然後再.....
因為我cache整個vcpkg root都能作用，試試看?

**Comment by robertabcd** [comment]
我是設 cache\vcpkg-installed，設 vcpkg\installed 會有你說的 clone 目錄問題
我以為是因為整個 vcpkg 目錄太大才問說要 cache 哪部分的

**Comment by craftwar** [comment]
整個vcpkg cache會把src和obj...etc一起cache進去，沒必要才問你該cache哪些
看console log好像是有超過100MB上限，我也不知道為什麼可以用
我的做法是clone到別的地方，再copy回去，比copy binary資料量少一點
至於下那些參數是因為我不確定vcpkg會需要檔案哪些屬性，就把一堆都加上去了

我想到更好的作法
1)
把vcpkg\installed連到cache\vcpkg-installed，這樣根本就不用copy了
check if !cache\vcpkg-installed exists, create cache\vcpkg-installed (自己改powershell，我不會寫)
mklink /j vcpkg\installed cache\vcpkg-installed
可能要先砍掉vcpkg\installed

2)
或是你要把git respository用zip下載解開也行啦
因為appveyor上的fetch不支援https的樣子，我懶得試就用git clone了

**Comment by danielshaw42** [comment]
vcpkg 的 `export` 命令也是可以用的
[https://blogs.msdn.microsoft.com/c/2017/05/12/vcpkg%EF%BC%9A引](https://blogs.msdn.microsoft.com/c/2017/05/12/vcpkg%EF%BC%9A引)

**Comment by robertabcd** [comment]
經過長時間奮戰，現在 AppVeyor 會自動 build 並 draft release。我先關閉這個 issue...

**Comment by craftwar** [comment]
AppVeyor加入vcpkg了
[https://github.com/appveyor/ci/issues/1076](https://github.com/appveyor/ci/issues/1076)
