### ISSUE TITLE
讓 BuildMenu 能在非 big5 系統下運作或是移除他

### ISSUE THREAD

**Issue by robertabcd** [pcman-bbs/pcman-windows#8]
目前嘗試弄了一個不用 BuildMenu 的版本：
https://github.com/robertabcd/pcman-windows/commit/16a48eb737bd4dc6313a9137433e7307ee1ae6c1
想問一下 @kidwm 或是其他以前的 developer，
為什麼要把不顯示的 Menu 也放到 Resource 裡？
是因為他會自己管理 Accelerator table 所以這樣比較方便嗎？
另外，用 BuildMenu 建出 UI 檔的目的為何？

**Comment by kidwm** [comment]
我只是個專案看守人，不是開發者，這大概要等其他人回答了

**Comment by robertabcd** [comment]
這是不是要召喚 @PCMan 大大m(_ _)m

**Comment by PCMan** [comment]
這個東西是歷史遺跡 QQ
當年不太會寫 code 的時候亂做的，偷懶把一些設定直接 dump 進 binary file，包括各種UI &選單的 customization。可以的話我是很想移除掉

這個 UI 檔儲存了customize 後的選單結構 + 熱鍵設定
如果要拔掉這些，那就要實做對應的文字格式設定檔
然後在 runtime 幫對應的選單項目加上熱鍵說明
例如 Open File \t Ctrl + O

**Comment by PCMan** [comment]
@robertabcd 其實我一直很想把這部份改掉啦，以前年輕不懂事亂做，結果一用十年...
把沒顯示的 meun item 也放進 resource 單純為了方便管理而已，這部份其實可以拆掉。
那些東西是在自訂選單項目和熱鍵的時候會被顯示出來，如果不用現成的 menu resource，就要額外自己管理一個選單定義的檔案，有點小麻煩 (雖然後來發現還好...)。
但是要拔掉這塊的話，熱鍵的處理就需要在設定檔多下功夫。
例如如果是 ini 設定檔，大概會需要這樣的設定:
[Hotkeys]
1001=Ctrl+O
1002=Alt+D
...
<command id> = <hotkey>
然後執行期的時候 parse 設定檔

1. 在 menu 內找到該 command id 對應的項目，把熱鍵字串加入到 menu text 後面
2. 把 hotkey 名稱轉成 virtual key code & modifiers 然後在 accel key table 內增加這個 entry
3. 自訂設定的時候要正確的把這些 hotkey 寫回設定檔 (key code 轉回名稱)
以上... Windows 都沒有 API，要自己做，但這裡有 code 可以 reuse
https://github.com/pcman-bbs/pcman-windows/blob/master/Lite/Hotkey.cpp

@robertabcd 你有興趣做嗎?

**Comment by PCMan** [comment]
@robertabcd 忘記說，如果改了設定格式，那還是需要保留原本的 code 用來匯入舊版設定檔，否則使用者原本的熱鍵設定會遺失

**Comment by craftwar** [comment]
不建議用ini file，結構上管理上會比麻煩，還有擴充性的問題
忘記encoding有沒有問題了，很久以前我寫win32是用xml
但是windows的內建xml api真的很難用 (要到用com)
XML, JSON 等支援unicode的應該會比較好

**Comment by robertabcd** [comment]
我不知道可以自訂選單，看來要拔掉 BuildMenu 需要改不少 code。或許能直接 check in UI 檔？

**Comment by PCMan** [comment]
@craftwar ini 好處是 < 64 KB 的話可以用 windows API，或是 pcman 其實有內建一個自己實做的簡單 ini parser，然後格式也很 human readable
Unicode 的話一般業界通用 UTF-8，但是 Windows 慣例是 UTF-16 + BOM，這的確很討厭
XML parsing 很慢而且 XML parser 通常很大，當然 pcman 其實也有內建一個功能不全的簡單 xml parser 可以使用
JSON 相對滿理想的，但是 JSON parser 現成的多半都很巨大，我自己是比較喜歡 rapidjson
但其實簡單的 ID -> key name 沒有 encoding 問題，全部 ASCII，在這 case 用 ini 非常合適

**Comment by PCMan** [comment]
@robertabcd 其實我是覺得可以的話最好把這些 refactor 掉... 可以再戰個幾年
畢竟整個 code 不能 unicode 化很大一塊是卡在這裡。
我自己因為現在沒有在用 windows 所以就比較少有機會動這些陳年 code
如果你有興趣改，遇到問題我很樂意提供各種協助
最終應該可以做出純 unicode 的 build 才對

**Comment by robertabcd** [comment]
我目前沒想到其他方法可以避開編碼問題，改寫成 unicode 看來是大工程。我滿想先把 release 搞好，畢竟時間也不多。

**Comment by robertabcd** [comment]
我成功把 BuildMenu 整進 main program 裡了，這樣就可以避免 AppVeyor 上面 build 亂碼的問題了。我先整理一下。

**Comment by robertabcd** [comment]
用這幾個 commit 把 BuildMenu 移除了：
f5304e9ad24ef058e6a6ae2c9294bf08831be4fd
88af247ab17c3f910ab1fde573137161745bdc3f
852a56878cc10f5909cc63429a26cf4d40bd2385
d5982892cc2ef053c94fdaef607356614aeb8247
user 每次執行會嘗試 load UI 如果沒有檔案，會產生 in-memory 的 UI 檔來 load。
