### ISSUE TITLE
pcman combo 9.1.5安裝檔提供

### ISSUE THREAD

**Issue by name2name2** [pcman-bbs/pcman-windows#9]
我這裡有 pcman combo 9.1.5的安裝檔，
可提供管理員評估可否新增到Release清單

下載連結為: 
https://www.dropbox.com/s/m36ysqohswmknf2/PCManCB.exe?dl=0

我好像之前從OpenFoundry下載的，但距今有點久遠不太確定

**Comment by kidwm** [comment]
但我們有放上最新版 9.4.2 了耶
https://github.com/pcman-bbs/pcman-windows/releases/tag/9.4.2

**Comment by name2name2** [comment]
喔本來想說連歷史版本一起放，提供更多下載選擇 
(若此理由ok可再評估加入，謝謝~
